#!/bin/bash 

#mostrar tdoas las direciones ip

echo "mostar todas direcciones ip de la red"

arp -a



# ver la version del sistema operativo

echo " ver la version del equipo del sistema :$winver"
winver


#curl de personaje rick bailando

echo "rick bailando  meme como los demas "

curl ascii.live/rick
 
 







