#!/bin/bash 

#mostrar tdoas las direciones ip

echo "mostar todas direcciones ip de la red"

arp -a



# ver la version del sistema operativo

echo " ver la version del equipo del sistema :$winver"
winver



 #curl de personaje rick bailando

echo "rick bailando  meme como los demas "

curl ascii.live/rick

# Mostrar la configuración de la red
echo "Configuración de red:"
ipconfig

# Mostrar información del espacio en el disco
echo "Espacio en disco:"
wmic logicaldisk get size,freespace,caption
 







